### ISSUE TITLE
非アクティブなissueをクローズするbotを追加

### ISSUE THREAD

**Issue by jonghyo** [openstandia/Nextjs-docs-ja#259]
**What**
一定期間更新のない非アクティブなissueを自動でクローズするbotを追加する

https://docs.github.com/ja/actions/use-cases-and-examples/project-management/closing-inactive-issues

**Why**
- issueが完了していてもクローズ漏れが発生し、issueが溜まるのを防ぐため

**Comment by kannoixia** [comment]
PR:https://github.com/openstandia/Nextjs-docs-ja/pull/293
